services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - /home/minecraft/data:/data
      - /home/minecraft/plugins:/plugins
      - /home/minecraft/mods:/mods
      - /home/minecraft/vanillatweaks-datapacks.json:/config/vanillatweaks-datapacks.json:ro
      - /home/minecraft/vanillatweaks-craftingtweaks.json:/config/vanillatweaks-craftingtweaks.json:ro
    ports:
      - 25565:25565
    environment:
      TZ: <>
      LOG_TIMESTAMP: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "FALSE"
      EULA: "TRUE"
      TYPE: "PAPER"
      OPS: <>
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      CREATE_CONSOLE_IN_PIPE: "TRUE"
      RCON_PASSWORD: <>
      
      USE_AIKAR_FLAGS: "TRUE"
      MEMORY: <>
      
      VANILLATWEAKS_FILE: /config/vanillatweaks-datapacks.json,/config/vanillatweaks-craftingtweaks.json
      
    tty: true
    stdin_open: true
    restart: unless-stopped
    
  mc-backup:
    image: itzg/mc-backup
    depends_on:
      minecraft:
        condition: service_healthy
    environment:
    
      RESTIC_HOSTNAME: "Backup Service"
      TZ: <>

      BACKUP_INTERVAL: "24h"
      PAUSE_IF_NO_PLAYERS: "TRUE"
      PLAYERS_ONLINE_CHECK_INTERVAL: "5m"
      
      RCON_HOST: minecraft
      RCON_PASSWORD: <>
      INITIAL_DELAY: 60
      RCON_RETRIES: 5
      RCON_RETRY_INTERVAL: "60s"
      
      BACKUP_METHOD: restic
      RESTIC_PASSWORD: <>
      RESTIC_REPOSITORY: /restic-repo
      RESTIC_ADDITIONAL_TAGS: mc-backups
      PRUNE_RESTIC_RETENTION: "--keep-daily 3 --keep-weekly 4 --keep-monthly 12 --keep-yearly 75"
      
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
      POST_BACKUP_SCRIPT: |
        echo "Backup complete! surely..."
      restart: unless-stopped
      
    volumes:
      - /home/minecraft/data:/data:ro
      - /home/restic-repo:/restic-repo

  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while true; do
          if [ "$(date +'%H:%M')" = '10:00' ]; then
            docker exec mc-server-minecraft-1 rcon-cli "say Server will restart in 5 minutes!"
            echo "RESTARTER: shutdown message sent"
            echo "RESTARTER: restarting in 5 minutes"
            sleep 300
            docker exec mc-server-minecraft-1 rcon-cli "say Server will restart now"
            sleep 10
            docker exec mc-server-minecraft-1 rcon-cli stop
            echo "RESTARTER: server stopped"
          fi
          sleep 60
        done
    restart: unless-stopped
