services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - ./config:/app/config # Configuration happens here, not in ENV variables.
      - /var/run/docker.sock:/var/run/docker.sock:ro # This is for docker integrations.
    container_name: homepage
    ports:
      - 3000:3000
    restart: unless-stopped